
# content of /src/main/resources/application.yml
spring:
  datasource:
    url: &dbURL jdbc:mysql://localhost:3306/peergame
    username: &dbUser projectuser
    password: &dbPassword wgnd8b
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update